title: Nam Phan (Nick) # your name (or website title) here
logo: "images/14053713_1082806561756213_3866850695488721003_o.jpg " # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  - Undergrad: International Business (Hoa Sen University: https://www.hoasen.edu.vn/en) 
  <br>
  - Master: Analytics in Northeastern University
  <br><br>
  - Concentration: Statistical Modeling 
  <br>
  - Skills: Python | R | Tableau | Power BI | SQL 
  <br>
  Facts about me:
  <br>
  - Interested in Machine Learning, Deep Learning
  <br>
  - Hobbies: Watching Movie, Travelling, Soccer
  <br>
  - Gentle | Friendly | Easy Going 
  
  
  <br><br>
  <a href="https://www.linkedin.com/in/namho-phan/</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
